export const AGREGAR_GASTO = "AGREGAR_GASTO";
export const LISTAR_GASTOS = "LISTAR_GASTOS";
export const ELIMINAR_GASTO = "ELIMINAR_GASTO";
export const OBTENER_GASTO = "OBTENER_GASTO";
export const EDITAR_GASTO = "EDITAR_GASTO";
export const COSTO_TOTAL = "COSTO_TOTAL";

export const FILTRO_CONTACTOS = "FILTRO_CONTACTOS";
export const OBTENER_FILTRO = "OBTENER_FILTRO";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const MOSTRAR_MODAL = "MOSTRAR_MODAL";
export const OCULTAR_MODAL = "OCULTAR_MODAL";

export const FILTRO_GASTOS = "FILTRO_GASTOS";